const CHUNK_SIZE = 1000;
const TABLE_NAME_PERSON_MF = "SCHEMA.TABLE__PERSONA_MF"
const TABLE_NAME_PERSON_IK = "SCHEMA.TABLE_PERSONA_IK"
const TABLE_NAME_CONSENTIMIENTO=  "SCHEMA.TABLE_CONSENTIMIENTO"

module.exports = {
    CHUNK_SIZE,
    TABLE_NAME_PERSON_MF,
    TABLE_NAME_PERSON_IK,
    TABLE_NAME_CONSENTIMIENTO
}